language: csharp

os:
  - linux
  - osx

sudo: required
dist: trusty
osx_image: xcode9.1

env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
    - DOTNET_CLI_TELEMETRY_OPTOUT=true

dotnet: 2.0.0
mono: latest
addons:
  apt:
    packages:
      - gettext
      - libcurl4-openssl-dev
      - libicu-dev
      - libssl-dev
      - libunwind8
      - zlib1g

before_install:
  - git fetch --unshallow

before_script:
  - chmod +x build.sh

script:
  - "./build.sh"

cache:
  directories:
    - tools

notifications:
  slack:
    secure: S6qmUFLLPAUvDtTCHyVRwMXZFIXIJCApBFNQw/0tAU7bqeqsiNL5+ga4Or1KlOT9HXy3HxprR1sN53fnfW9qEsdtWzCwMhYScG1ljjIs2s7jEjWb14V9X4ufvq2/KwFN2F6QVyEbzq74wJc7HzwpsNRO5pPlRaSxabB7JDdk/Qw=
    on_success: change
    on_failure: always
