language: csharp

os: linux

sudo: required
dist: bionic

env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
    - DOTNET_CLI_TELEMETRY_OPTOUT=true
    - DOCFX_SOURCE_BRANCH_NAME=$TRAVIS_BRANCH
    - secure: kReI3QWEt5AqP92v/z2ZLO8bFOSgAXcGpsIFUHzFGpetHw8poBFW2GK+ZXbxGXddRfDVsFxptBbAxMihuhX6ljHyOcxkqAsSvs4C+s+XqUtR7oCi4ye2nXhSL30mJTk/o6KZTTL7/LomR9FONf7/3ws26uf/fcstpvNTbiiuV6Y=

dotnet: 3.1.301
mono: latest
addons:
  ssh_known_hosts: github.com
  apt:
    packages:
      - gettext
      - libcurl4-openssl-dev
      - libicu-dev
      - libssl-dev
      - libunwind8
      - zlib1g
      - unzip

before_install:
  - git config user.name "Travis CI"
  - git config user.email "noreply@travis-ci.org"
  - chmod +x build.sh
  - chmod +x travis/*.sh
  - "./travis/fix-branches.sh"

install:
  - dotnet tool restore

before_script:
  - chmod +x build.sh

script:
  - dotnet tool run dotnet-cake -- --target=Travis

cache:
  directories:
    - tools
    - $HOME/.nuget/packages

notifications:
  slack:
    rooms:
      - secure: R4MPX1npR0bqYK+4Ce/TF4ECjV0UETKEO/3/xZ2ZGibdHKU0IfPjD81uY//qaTldD0HgOu0CTEseocnjEYeit01QdUDjjdrL+/F4t0SNabBomjt+V5COUXXePHqov9lB89yBn+6GfbpkPjS89dW8bGv6SqfTZr3G1hNBMUhl96g=
    on_success: change
    on_failure: always
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/81f38691a11c835a83c9
    on_success: change
    on_failure: always
    on_start: never
