language: csharp
os:
  - linux
  - osx

sudo: required
dist: trusty
osx_image: xcode7.2

env:
  - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
  - DOTNET_CLI_TELEMETRY_OPTOUT=true

dotnet: 2.0.2
mono: latest # Needed for Cake

addons:
  apt:
    packages:
      - gettext
      - libcurl4-openssl-dev
      - libicu-dev
      - libssl-dev
      - libunwind8
      - zlib1g

before_install:
  - git fetch --unshallow

script:
  - ./build.sh

cache:
  directories:
    - tools
