language: csharp

os:
  - linux
  - osx

sudo: required
dist: trusty
osx_image: xcode9.1

env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
    - DOTNET_CLI_TELEMETRY_OPTOUT=true

dotnet: 2.0.0
mono: latest
addons:
  apt:
    packages:
      - gettext
      - libcurl4-openssl-dev
      - libicu-dev
      - libssl-dev
      - libunwind8
      - zlib1g

before_install:
  - git fetch --unshallow

before_script:
  - chmod +x build.sh

script:
  - "./build.sh"

cache:
  directories:
    - tools

notifications:
  slack:
    secure: "R4MPX1npR0bqYK+4Ce/TF4ECjV0UETKEO/3/xZ2ZGibdHKU0IfPjD81uY//qaTldD0HgOu0CTEseocnjEYeit01QdUDjjdrL+/F4t0SNabBomjt+V5COUXXePHqov9lB89yBn+6GfbpkPjS89dW8bGv6SqfTZr3G1hNBMUhl96g="
    on_success: change
    on_failure: always
