image: Visual Studio 2017

version: '{build}'

pull_requests:
  do_not_increment_build_number: true

nuget:
  disable_publish_on_pr: true

environment:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  access_token:
    secure: ZWDltUxdxnkQ9jf+HC+g7Hxm4Nke7H7AtMv4NWu5Uf+ZP4DV77Vc3C2B87moIUK0
  deploy_key:
    secure: n6KrDebbQH5qVYY4l6ZfPWivxvlLpClKqFvOzmvEn6RSYnp74gHTz0A2HjIgUdpIPAEqQrF+J3W/cYOKsxqI+BCbBp55kXsj+BoEhXdpgrwj79NRlDqEohm+3Fx2DDRglqDX33/8huqHkyBSE4f5275UiGUcWXU2xAf5JJu95OJFjQUDao5fnYtkV4EwjqSqukBolobiheITSlyxJaowj+/K1h0/u/4RgKGdMa6V+XlUttKer18mWt2yl1rItRvyRbMkd6KnSgjUWC3k/2FR11CfPsQ3p41uxNj/LMJ3lkc/7pxwFlNv8RJ0dB8kONea75BP2WzbdAkeeKQnendpD3DVcXZgWYuxnZOrTR+l4WNRxuykyqLSWnti/yjMaZ+9DksC2XQ1teL9R8DDUBPF4VWRT2h7WAcxmiKCZ730UQoIWkAQ9jtTwy0HE8wsmzWDzjit1FLgErSlhLoilSFO/QMc2A1SEq0kS3cHF/Lp/3cUp8fb7lsiP0dEMKE1v/+kDVMaXfZ4skIz8W/6LzEwdmJWwR0lQvXpG26T1RZZs2AghOavwQflT3kSOKIP83Hvf/z2lZZNJA+N3S/awhyOrKNtw85DUheuVUBMK0gEjz2OdPmtzfxuhfSgoKT4qIHKjKr6JUqSwzbPCyLiTYkzZSJdp62HqrPYU7jn1OTATriWK+MzJymPb21QNK5Mp9ZhzsdqsbqPP0fOy4pjF4rNRhPXo2NYvDrEsp6Zvx98M5p6HqtQBSEZFFLFcY/qpQX6Og3Z+DFxOCd3gtQyP2laVP/HeBmxOlAkNWjke7Pw+BKwlUXguSjdu9JSAAmFOgEpDYfuVCf8s92smc6qNFdB5RKmoOKodBe6FmxivK6hM7YOmjF9oJMnJlQceApxmckFtaODOCFGMwPej+Mrp+hSIqobeZ5YEXo1mYfXK5Z82pnXkbhJHhtxcPElGUIEN89XgYw6me+rRy0nOfuA7iYws9kHYo2EL7WGHOZK5tsxH6UDppyVasJs3OorugufsahFf5zNWAwsPYhxYdu9cWVecfRg//+c8icFP7gmbiS9Wc5yB8ITK18f2ZTNFYj26g83wFEkReuukOietL3lMo0fRA3/4tvMv+7dSeG3ik6tNHdIgCBbyiHRLu6gs1UywK+aIqZvtKOEULg3Z8kNvJbgeJx7i1vBucdxM/I57crh8QPquCwl0iE2PDO+tAPRjOPST0P3PymfCOdJn3LY28OZOm4kIPlJ37K8PonYmDFRzLBZm4+75zU72I4VR5cC5Xpzrrhr5UVRp9M5/OkujLW8Xg2jtRUSh5igHBq/RauG/AfwOAJ2HZTHzAD7JQTRbokj93+OrUjSM5pSDaRHGNlrnFa5KRZVYod0oAWEJJbfZjIpmb6DtapYi5396p+FTp3dhOLO9Cf1GkoHGAaOJx2JEQmiFgKQXQpuev+ZVUWPuz4rGGd2kz+D9I7rupEHFgcanzT3zJ5NG2WntuHD10b9iV/zjXR43qlN8mGTEPCB68dRpwE4ex82NPBRKNgxqpJVepKbmNc22g6eCuOEt2/MABUEE6JZ2twDLpiGFrSp9icV1LrRRaznvOlGetDjnRdSeRz2+lMPa2YEygEN9NFLuZrRXOJzAtXSUILj5b3RZC59RcphP5oPT87QnnBM5J5kzHq0f8oZ/3w4wFJzlVenTogq6Ma73CcRgHUS1sFF/q45n9NcgW0dp4KyxRLBmlwMLYS/PcB8j2s6V5X01iSjyn63ozl6nTLB2wFflhsLZPrUDEEpLLIwNMUN36skrnLD5kb62Uu59y6WAlCjURYkx3/ZDSgHMnLQJWA9RrD34iH+4cIXxPLGm2euBMmMg+2rrnyxbNRzQ2lY1hvbSRzhChkRW7guDnZ0Ml2ydY5PmqrSVwBFPMz7DT/qDijonLehbHIb6UK+RKulXmgs0oGAYSO82jISc498u4hkik5vH765wG+Iu6ZZAv66m6YI3OdN/7W2FzE4pcNtRAA3zvpF1OunreVrJQ/SXESURsZoIbulK/Iee5062bzPAbn9UdqobDWq4HJHft26LkhFp4d7w/JRCJ5bKMCMN41AEdca0If4OdHfLpDKK4psioPVnmfNnXMFzJGmUm5rkBLThiIhZjpsa1ljYSOs9X6Wr6TPrbk+iaZf+5i4Qjtj2jFa2WK1Zp++9QtK4U8HDEg0y8Sua17Dktd0XdePT19tOCPeXMrjEwGkrkvG4ppeVFOXMZcb6chWHp/17kXRpW5mZjUXQ97tjw7Gw8ofwqh1SXCDQRW/472/sqJb3Dyp8sBbZFWEGeP1v4v1YcUeg5l7MG8XRKx9IBexc/l4gRtKM+PPatUDJtot0biCE6ByUbdzKU3xlySNbRYdyl7maSXeoKpoQuDQuzrnrQaLCCK+/WqvJE2kqBsPqPSR5PhOleaf0XnhTh4k1/gbZn351F3TnCPFvKcF1QFvpwVTA1cIfQPEcSA9Vd90OKm3eABQNnhhFzcqVBbX5bvb/lvXOmZToJwHkC4Q75iYfXkvPhbNKMNaFDXCSz4X5IUeGqvEO5vcwTw4HwQ9vT1E6d4/NkVOO7afPhVIyh0hxfKH1evHn7Bb6iIQ4TXAYIosTgIkF3yTs8qnZaWC6J9MxLD9DU3jKFXTD+BIgmrHwAtqJ+rhuBPHhhlI3wLkurtzGnfkmQfW03owWDNlGIIGhi8s/YJ7+j1Ko68kyHKRnmYBYTxBatNd1JdDpIGmrgd9E0UdXAH22Wly/48pow+FSY0TmptrsHOsbQ0vnfiSZDH0H8XeIOX3q9cZZqk7zRNTjWdGBuUpwSFBIHRLwOnf2GAPcIZaINln828XTPK7MJEthwWtfsX0y32Nnn31wyAJB6xOg/oHLewIELzihdWx1SBf5D33Zly4s0UrxDfhlkmy9Tt9+gTbZ6+VaNOrfRc8W1Ek6WJ6DLRvP4jUFZL6CKTz9Ul/omRMUhkMnZ/d4To0aHvLtHoXsP3BLyz/xDxkY1FS6pTl9gSAvO+nR4ziUiMtyXzlmxdEDwYZHJp/sjkjGv+1D+n9Z9Yy5jxMRxhEF3iMEclNJjxzxCE3rMG3zve02GlWCDTvywI4E+y3zZ3hO0BT4OuCSBZbx28uKQTmQjxgCWkE4Wl+/SH1F06A1qmU9kAFarZ2iky7vR0GFACOrqg1OFNGj6lZcWWF00uCtNn/AFdC7ldtFXn4v+rweQQkBmYC207A7EqZ8KYD2ylTWAfpeW9pyN/Zk5HsyQxcZ0P6mXd+O43tk8ZzHd3gnRcStvv1+miOoL/PkUsWKpanz0rCidv4NQKVhrThm3yiCV1/xg2yko7f5Oj4hqrkdEXbghMRRr4z7KBokqmRrNDYgZPhPYIMPe8BoDMxN3/rCgnApI0MlhV3O4VTuTWPBJiSMacFi0iTVtcI6bxOEi1xfZdAMw13nESMIhG+okPNpDy06DhKLh7wHox1V357SfcSA4fKHswBlL15lVF+b9sXfJZKcf30tadhxv8iMSKMjfMHFiXp7MdJJs9m76ySIkhIcLSpsDgTESNgk31FnU5Hb65V1GSV/gKaveoBDCeFxEu/+/Xv/tYjGNEJtkfYoKiw0+5mpfSa/xNst93yqShl5Vm9vnZU5nKPfj1hlzp606HX3OMs1lBOzfOXCiH2Fl9HNCuHsKMLgFxhEz9TNb7Y0M+EQaA0VcUhI+QkbWQdtAWWcJUuDSSHF8+eHURlycORaG3omdxAgPrajumGn2NlDg079GQVM11lHf9+6IzO/w051FkUtZxA9r0BbDdGjR8K8J76q6NTmgjghmAYc/re6jtzvuidwzMSzm02fT0DJbzNZYd9tFdUjEwFktCVUPTJGgfRJueip8gt6SMWHBXT4hFo6nK/fjKo5MauHydmu4joEvqgdGkOFoQMXfelo7nJtRInkn+Jw1/dCMSMDgpPArDru3qkpf+JKbmz5w+TCZIYgLkKkG2WJC7cAz1nNnd5L7zc2SzY46PS9osLsBBnvrAGKciuwk1cY/DA2/A6OeeL/ifl0SRLtWIFReyEp9B41Gdq05tD39uoO3owcLuZfBGUi+F0j10IAJUnICrNJFaPGD0+Zn8tR/YvopH0G4RUtAJVD6yNUuLaAKB/RQuvr4zJSNDqiHSCdonpb3yGFm+4cSN99I0L3S5rZ4m/hvWJGthU27LWLmEA9qxuhVWU4VNt7utLeg4k+u/MkIrOX6GFUMZ6+l4qX/9tfZrJoPKfcOW91u8X+w==
  COVERALLS_REPO_TOKEN:
    secure: /52HsSigAGXgmKFcFuNjgC3PPMIUkarMod0zxTDesVS5VNpKCyeqdBY3Ssy3R3Mg
  APPVEYOR_RDP_PASSWORD:
    secure: wChw9Tx7JVk3HvjG+ROsKpWWqwWx88uQ5xT8eOrO8lc=

cache:
  - tools

init:
  - git config --global user.email "deploy@appveyor.com"
  - git config --global user.name "AppVeyor CI"

install:
  - choco install docfx -y
  - ps: $privkeyContent = "-----BEGIN RSA PRIVATE KEY-----`n"
  - ps: $privkeyContent += $env:deploy_key.Replace(' ', "`n")
  - ps: $privkeyContent += "`n-----END RSA PRIVATE KEY-----"
  - ps: Set-Content $env:userprofile\.ssh\id_rsa $privkeyContent
  - git config --global user.name "AppVeyor CI"
  - git config --global user.email "ci@appveyor.com"

build_script:
- ps: .\build.ps1 -Target AppVeyor

test: off

artifacts:
- path: .\artifacts\**\*.nupkg
  name: NuGet
- path: .\artifacts\**\*.zip
  name: Archive
- path: .\artifacts\opencover-results.xml
  name: OpenCover
- path: .\artifacts\coverage-report
  name: Coverage

deploy:
- provider: NuGet
  name: production
  api_key:
    secure: 0kgF06I+L8BAOvMagk7Muw+mkYQnZXAh+HO0S4Rnbr4BSuKWVCD5lBd5N4mpyABJ
  artifact: NuGet
  on:
    appveyor_repo_tag: true
- provider: NuGet
  server: https://www.myget.org/F/chroma-sdk/api/v2/package
  symbol_server: https://www.myget.org/F/chroma-sdk/symbols/api/v2/package
  name: production
  api_key:
    secure: vG2UFV8FgS2hYY1QfkXshHO9hvm3rgV2pEKXB7WBDR/Y+qHp1N+audYtqmfdD1NB
  artifact: NuGet
  on:
    appveyor_repo_tag: true
- provider: GitHub
  description: Automatically created by AppVeyor.
  auth_token:
    secure: ZWDltUxdxnkQ9jf+HC+g7Hxm4Nke7H7AtMv4NWu5Uf+ZP4DV77Vc3C2B87moIUK0
  artifact: NuGet,Archive,OpenCover,Coverage
  draft: true
  on:
    appveyor_repo_tag: true
- provider: NuGet
  server: https://www.myget.org/F/chroma-sdk/api/v2/package
  symbol_server: https://www.myget.org/F/chroma-sdk/symbols/api/v2/package
  name: development
  api_key:
    secure: vG2UFV8FgS2hYY1QfkXshHO9hvm3rgV2pEKXB7WBDR/Y+qHp1N+audYtqmfdD1NB
  artifact: NuGet
  on:
    branch: develop

after_deploy:
- ps: .\appveyor\deploy-docs.ps1

notifications:
- provider: GitHubPullRequest
- provider: Slack
  auth_token:
    secure: q1G3kdpLxdD6RzSNVDZoEktdr3pcUY5KFXqxaV3mzGWWgOAyREl0ZHBNQUSWTLCy
  channel: '#colore'
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true
- provider: Webhook
  url: https://webhooks.gitter.im/e/a034d0036043d620fe38
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true
