image: Visual Studio 2017

version: '{build}'

pull_requests:
  do_not_increment_build_number: true

nuget:
  disable_publish_on_pr: true

environment:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  access_token:
    secure: ZWDltUxdxnkQ9jf+HC+g7Hxm4Nke7H7AtMv4NWu5Uf+ZP4DV77Vc3C2B87moIUK0
  deploy_key:
    secure: EDIJ4kKXadlecMeADyCFoxOY/HaOozWKAUTqfkk1sQQSMGirGy5+hWiIz4gj77hHmGUy7roCZSG40JMAxk+ejDVumgm53oHTnMmsrUefkpN4oB/rUBqkBSkx1VD+SdFmaGBpxvoIiMCf57U33cBLvykbC/O1hZdtPRmoye8M7S8Li3ZOMHhX9gPGFt0NeZruSO1i0SuSBdYZu4jLCIZmLS0AWrQYSZ0y8389LELbVhyYlPuhNL+9Ql41SP98OaVrE2ypfhcJen/9orBIHkZ9fD/eiyFrSOyTtJamT0mQTOXialwPqBboqvmuwPfv5i+X5BzN+lVtpIiFEou4Mff7AqS64abh8fSyjZQWs+GB+jjTnI7xOOmtRHNL0LBc/lWBxe6rVqqvV22ly61OIkdE11uTFnN9WrQvjNL5Isi4OsQHc6K5l34xMtzjViE5xMlqu3HYvWopjeXSbuUl81jjLG58WfGDFGLkTHFaBKfJcHp4nrUTAt8K7q3WEsqPRdoxIgX7Z2sSKkpupiJqHM/lsQVsYHse2swmdBYS+aWjuLZ+UcEuuXfQdVF5SEvlxBo9Qw8tdaNz4xuiKWot3nDAenprAzjxI2Qtai5VQK2ygBLSLK4x8bVcff33kwV1zzyJ9rs4wR7y677INrwi6Bc5EDB5I2yuPgGVO4QXNOGd8UgKMlzILAhv5XnO/3kk/ShmkvCo/88XbFFaRX2hvHQv1h2hal+8MxB4e676C/J7/hUvrv/zu2WlEgon5n7EXWTwTDLdoj81eGyOX95CdwBzjYvUF999aU5M3yu+eAf31oAeMtU1lpdvuGivvksW3jpIXRTHLaPaB40j+tdwGwfIJivUAm7UdHSycwBpPgSAy+ftczxZzYa935H+xp/U1T0INFaJ5L1DuiNq7bEcMxNOejSHzfgOme3tYKuqxLfxz1GAokrDSttkqLDEInGm3EswoCk5pd1cRk+c/DhI/cNXxPmDK+uraCb6bAkyWbAmXiz+Rx+mDclkbknmzjwun7RzF3P9/sWxq2zJm1Qplgzx/aQgToDNiu5R1Ews4Djr0YjQcdQCgSf8n2J2QxMqmTPBrAyRKqh+JVyhNeiVpXXiGwaOaWUwIYPM2xB+1LjWcIgj7tpY6+2EFylqFkCMU4mp0uc9EMMa9vAOh/A9VtppgT0GfE0UUiTSC6uzvv+fal1jt/aYy4QkGqdxjMUfCTMvmixOBt05dI9DuIWpo0Djh7kX9AuGAhO1Co+52+LnpCT1pZDN5OChP6aabJDSCV5HkIoKPbeyW2XVvQksQecktjVIit7E04P16Q/xxTPmHe1vJdxSLW+ANvFGiQYPrIp5PljcsUR3V/by2WrgHzP677JNGCYAL6HJVpWY/JRsgOyQBNspKNOcjkUjEKgBgTBWlvRSRavOJUZ8noT5O1/5tliZWGSw9NAIOQ/o7uuYlaDby1ToaC/WGHwgFCdP9V2omGfgsjNh/V4SlNuuIeRqMuC5v5NFWEMDDigBgrwv1qBlma1TvJvTcHnkgpOAAZuBhhIbiO/V65OSNKsO0i3AqpW31qkxD4dxq8EFj4SsLNlY82AGcqhwFFUHLrs71HIjMwBOd0nG8wQmbmo7b44Y4EnYfTR6N+feBTXJAGAuzkyBUXQxJli9dLkF5sEYCsS9/MwgOUn5hBOEZ6x98uIpXb/4nK2GEiB1AqN21IzoqReytZ8FB/wlhpSYf4yhc1dGEyi20VxgrMhd1+U8TpXxphoLzX4L2fKHXKjE3Hi3KH9bZemDUJVAGdchz4sle9dTjoZFu5mV/nedErsg/5Ch4AgpXjgILHpR1uPVs//SOF6SHPiWQmERPtMWi628sVD/7+1aEvY3yiACi11hY+0Q9V+S1W6UAwha9W4wf/zL0kZY0hxa2zFwIHJ6AX9KLGRoahLc9cXWFjFZ5hy2WAgXEk3H+lOLZTYeWs3s95zGaRizVaZ7MZexjfPBX5ZXCC1QK8K5RAt0FGaXEtc8hMlSEkn+0N4j4XY7V4L3hXCC27iWBA7KlzLFgzbE729q4PVB8ywLitxjNP2c3vRMMrT/vPbA3tAjFXnrscEg0VXQrpcD1YgnibltI/8NwMjaD1QIUZKxFMFDMM30JCSNMurhIrMymB2utIR0OP3xfd3hukP4//fZPmkvR7ukHloKjItr0Swp/qmLRGcUqHCSxfN5rAk4BNmrQRaFNJXY4X/9iOrnRGq+nsIBENtqFxvIzmeLdXiuQThcX2G1gIyjWXgMsji7R/EO2a9Y5XMWW9g6a94GJ8XCJ/N9HlCgVTEjyV1E70iDzR8+yKFuUyBFkuCYkReLpKiRtgaxUp/VZfOd7LIi6yOsN3CzHFQR4WbcVKNl3bccL3uwta1dDck+0qNNzK0cxoHyAAys+Rpszk/H9DafPJOfDu134sR861yX7HnUH6eyo465jB5VK5JIbzdMUgPz7BGv/h6xq1fYHIunGRIQhFmuDkfSkHWEM7TyXausck91Ue02tFY4rRIT5knsG1PjWPrMLprzZuuuFHTjTYhvzVC+zITvgBwj8gAeu6wnDpTvD5TLlrCRaTV2jfXA5LCKceo3fuJMPnvBlLS6T2q0iA0q/OsW34CI8D5de0HQBKWB7P0wCl3rJuKGzADIWXrgYlzX5m3zRvz3G7CQkGcfWrt5CXEZ9rqXXvJB/ra4UyGFQkbZYDVgSeLjtvtzwh2CQ0dkLQBWMr0e/eyDzHQ4bozVqEEcbNXnv08mD12kjatkmaUoapkChlkOriNFvdw9W6OVOeG07fVUAZ8HqjysBH0ydh3Gb9yvvUx/UigM6zyjVZ966KrnkDZo8hTNxJpqU6+riSD2zxj1Sjp5w9snmXsIcba7TLSbbGhOgePtIXjBprkZe3WsEgzea8zx/PJk6S+TvUS9nxkwFEvsa4HItmL2QKcms1RwdbHL/dKSnR0Z2D3RV4l157h+unOFBPudSuO/RZE2EHENT8LcfeJiHus9gfeDd1qqG1j5NJEohhUlJqnPEZf1TbHvK+Ypm10TfJ3ggDsZuELZGB0qfGG6fgV6Vs3h/9esLSTIDWHpsTMs4RjEk0zGi6b7v6udSty2/zNrXEOSkVqLZz8UV5K6XfiVOuyCJhB25GTa2Tg/38ai8tYu4hHrgU+X8PFy5/hG3DOekAI9FTMjHS8FfHTRFCQNeeSi5lzCDg9r//oFLtFCvVPC1OTcz7K3Hc5hWaNwLp94g7VBSd258oQL93xPBJJAkEGPMkhVqEkMjlGqY50XoYOKl93QNs6RUCg84m0par9ZOt2gj79fscRcM+GLCgB9r6qQ0cX8igO8Qi6dMU+vsgdM6h/XUl1a8tgI7EfZ7Ocan69IgRqOKSYX4GSqb617dya3gEGhFBXV4ZsY9r8pImS3lvb1Y0x73oOJM3Kj9oXNtEjXxs3CMYYtOSJKo0mcp9kCs5A8kVeJn4tquvAF71zR/hu1Ziotgv+/vtcpx8nOIoHWXTvDjl+dbdRALxehEJ6ODQ++3x+GPmaahu/SR2SQ/Tqw8XHk1HBSXPrzoVY+PAo6BxC/6IIN7fRfixD579v1pvEiWmpxsr4r8XR78QvG5yRLIwN8PvjtZPfFo0Y0A5fDDQFMvCQVInGfPPaUxNnyo3gWaETUHn6AI2Lj0tOWxcy9dSR+uB1w08nw5N6nRpZJgmZmJ34XB0XtkOVnxSobacfVJDn4HADAzNgzYZw3kY3u6VKHouDTcki/XkQiwUWO2gRj2uKEJODJ5l5vabezlqvN1MVnTR9+lk247+3lqG7CW4V13JFlFusbEvqbwZo4dGKVQh8AptryZo7quBxHW3rQO2yrraor5/aLiYjUShYpHw5i2mWPCeN/5tjJZhrgVOozKRDqzOXHGt0FXv+PhzzwmbryQsm/dhG2HILykLweREEf7wpSEFgEynAt+wSYmmL1pbFi0nE5ziNdw2OGNa2lsLiPiS5cwZcunONdZGVkF8Wpp3v60XmmQT0U38wiMK8X4QvUH9g213BEvKG2u/x5doEsP415z2IgkqUg8Zy8WbcJtgLQTzDUonYeGtmGeGjQTMWjm+waCeTXmk+8JDw4BOrWQfBeQ+Sb4cgX+8sgPoPsD0hiKTNp78ISud8R5uvOy5KXJDYTvSq+yAd7aDBgFqK0ODSPnF5crDrfGWIIX9PjdLIlaqc9EDIVpm97CErs+1RlkpjJ28VyjfoWKQ67AN5dUfEAPEWWJUReVuVE2v0yHLbh81dyX4HVXRlDByzSHiBmQ11qNRtC4exYHwWcNSwYJOC/g7u5OQ3njVgaNdF/yiY3gFlW1I6TKjlG7YcOvi+qkdo=
  COVERALLS_REPO_TOKEN:
    secure: /52HsSigAGXgmKFcFuNjgC3PPMIUkarMod0zxTDesVS5VNpKCyeqdBY3Ssy3R3Mg
  APPVEYOR_RDP_PASSWORD:
    secure: wChw9Tx7JVk3HvjG+ROsKpWWqwWx88uQ5xT8eOrO8lc=

cache:
  - tools

init:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
  - git config --global user.email "deploy@appveyor.com"
  - git config --global user.name "AppVeyor CI"

install:
  - choco install docfx -y
  - ps: $privkeyContent = $env:deploy_key.Replace(' ', "`n")
  - ps: $privkeyContent += "`n"
  - ps: Set-Content $env:userprofile\.ssh\id_rsa $privkeyContent
  - git config --global user.name "AppVeyor CI"
  - git config --global user.email "ci@appveyor.com"

build_script:
- ps: .\build.ps1 -Target AppVeyor

test: off

artifacts:
- path: .\artifacts\**\*.nupkg
  name: NuGet
- path: .\artifacts\**\*.zip
  name: Archive
- path: .\artifacts\opencover-results.xml
  name: OpenCover
- path: .\artifacts\coverage-report
  name: Coverage

deploy:
- provider: NuGet
  name: production
  api_key:
    secure: 0kgF06I+L8BAOvMagk7Muw+mkYQnZXAh+HO0S4Rnbr4BSuKWVCD5lBd5N4mpyABJ
  artifact: NuGet
  on:
    appveyor_repo_tag: true
- provider: NuGet
  server: https://www.myget.org/F/coralestudios/api/v2/package
  symbol_server: https://www.myget.org/F/coralestudios/symbols/api/v2/package
  name: production
  api_key:
    secure: vG2UFV8FgS2hYY1QfkXshHO9hvm3rgV2pEKXB7WBDR/Y+qHp1N+audYtqmfdD1NB
  artifact: NuGet
  on:
    appveyor_repo_tag: true
- provider: GitHub
  description: Automatically created by AppVeyor.
  auth_token:
    secure: ZWDltUxdxnkQ9jf+HC+g7Hxm4Nke7H7AtMv4NWu5Uf+ZP4DV77Vc3C2B87moIUK0
  artifact: NuGet,Archive,OpenCover,Coverage
  draft: true
  on:
    appveyor_repo_tag: true
- provider: NuGet
  server: https://www.myget.org/F/coralestudios/api/v2/package
  symbol_server: https://www.myget.org/F/coralestudios/symbols/api/v2/package
  name: development
  api_key:
    secure: vG2UFV8FgS2hYY1QfkXshHO9hvm3rgV2pEKXB7WBDR/Y+qHp1N+audYtqmfdD1NB
  artifact: NuGet
  on:
    branch: develop

after_deploy:
- .\appveyor\deploy-docs.ps1

notifications:
- provider: GitHubPullRequest
- provider: Slack
  auth_token:
    secure: q1G3kdpLxdD6RzSNVDZoEktdr3pcUY5KFXqxaV3mzGWWgOAyREl0ZHBNQUSWTLCy
  channel: '#colore'
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true
