version: 1.0.{build}

install:
  - nuget restore

configuration:
- Debug

platform:
- x86
- x64

matrix:
  fast_finish: true

environment:
  COVERALLS_REPO_TOKEN:
    secure: MFfyfqucK824o3YhdTCIzsccWHO+oHKnqR9veWZLwC1+1lMaXoZTtyvJHi2NwXUp

assembly_info:
  patch: true
  file: Colore\Properties\AssemblyInfo.cs
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

nuget:
  disable_publish_on_pr: true

build:
  project: Colore.sln
  verbosity: normal

after_test:
  - packages\OpenCover.4.5.3723\OpenCover.Console.exe -register:user -filter:"+[Colore*]* -[*Tests]*" -target:"packages\NUnit.Runners.2.6.4\tools\nunit-console.exe" -targetargs:"/noshadow /domain:single Colore.Tests\bin\%PLATFORM%\%CONFIGURATION%\Colore.Tests.dll" -output:coverage.xml
  - packages\coveralls.io.1.2.2\tools\coveralls.net.exe --opencover coverage.xml

artifacts:
- path: Colore\bin\$(platform)\$(configuration)\Colore.dll
  name: dll_only

deploy:
- provider: GitHub
  release: v$(appveyor_build_version)
  description: Automatic release created by AppVeyor.
  auth_token:
    secure: ydn12l0oWmrQy0gZiWsLypa0kzYDBjVqAzlrrZ1+s97QRsCYkK3aA4KigRtC4CVm
  artifact: dll_artifact
  prerelease: true
  on:
    APPVEYOR_REPO_TAG: False
