image: Visual Studio 2017

version: '{build}'

install:
- choco install gitversion.portable -pre -y

pull_requests:
  do_not_increment_build_number: true

nuget:
  disable_publish_on_pr: true

environment:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

before_build:
- ps: gitversion /l console /output buildserver
- cmd: 'ECHO VERSION: %GitVersion_NuGetVersion%'

build_script:
- ps: .\build.ps1 -Target CI

test: off

artifacts:
- path: .\artifacts\**\*.nupkg
  name: NuGet
- path: .\artifacts\**\*.zip
  name: Archive
- path: .\artifacts\**\*.xml
  name: TestResult

deploy:
- provider: NuGet
  name: production
  api_key:
    secure: 0kgF06I+L8BAOvMagk7Muw+mkYQnZXAh+HO0S4Rnbr4BSuKWVCD5lBd5N4mpyABJ
  on:
    appveyor_repo_tag: true
- provider: GitHub
  description: Automatically created by AppVeyor.
  auth_token:
    secure: ZWDltUxdxnkQ9jf+HC+g7Hxm4Nke7H7AtMv4NWu5Uf+ZP4DV77Vc3C2B87moIUK0
  artifact: NuGet,Archive
  draft: true
  on:
    appveyor_repo_tag: true

notifications:
- provider: GitHubPullRequest
- provider: Slack
  auth_token:
    secure: q1G3kdpLxdD6RzSNVDZoEktdr3pcUY5KFXqxaV3mzGWWgOAyREl0ZHBNQUSWTLCy
  channel: '#colore'
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true
