version: 1.0.0.{build}

configuration:
- Debug
- Release

platform:
- x86
- x64

matrix:
  fast_finish: true

assembly_info:
  patch: true
  file: Colore\Properties\AssemblyInfo.cs
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

nuget:
  disable_publish_on_pr: true

build:
  project: Colore.sln
  verbosity: normal

artifacts:
- path: Colore\bin\$(platform)\$(configuration)\Colore.dll
  name: dll_only

deploy:
- provider: GitHub
  release: v$(appveyor_build_version)
  description: Automatic release created by AppVeyor.
  auth_token:
    secure: ydn12l0oWmrQy0gZiWsLypa0kzYDBjVqAzlrrZ1+s97QRsCYkK3aA4KigRtC4CVm
  artifact: dll_artifact
  prerelease: true
  on:
    APPVEYOR_REPO_TAG: False
